App_Blog/urls.py
from django.urls import path
from App_Blog import views

app_name = 'App_Blog'


urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug:slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('my-blogs/', views.MyBlogs.as_view(),  name='my_blogs'),
    path('edit/<pk>/', views.UpdateBlog.as_view(),  name='edit_blog'),
    
]

App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change_profile/', views.user_change, name='user_change'),
    path('password/', views.pass_change, name='pass_change'),
    path('add_picture/', views.add_pro_pic, name='add_pro_pic'),
    path('change_picture/', views.change_pro_pic, name='change_pro_pic')
]

My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <title>{% block title_block %}
                Blogs 
           {% endblock %}
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}"><img src="/media/logo.png/" width="50px" alt=""></a>
                
            </li>
            {% if user.is_authenticated %}
                <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        @{{user.username}}
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'App_Blog:create_blog' %}">Write Blog</a>
                        <a class="dropdown-item" href="{% url 'App_Blog:my_blogs' %}">My Blogs</a>
                        <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Profile</a>

                        <hr>
                        <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
                    </div>
                </div>
            {% else %}
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'App_Login:signup' %}">Sign Up</a>
                </li>    
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'App_Login:login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </nav>
    <div class="container" style="padding-top: 20px;">
        {% block body_block %}
            
        {% endblock %}
    </div>
    

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>
</html>